### PR TITLE
Allow disabling addons on 404 pages

### PR DESCRIPTION
**Pull request by humitos**
It reads a META tag `readthedocs-http-status` to get the HTTP status code for the original request to the documentation URL.

It uses this HTTP status code to decide if each of the addons should be enabled or not.

* Closes https://github.com/readthedocs/addons/issues/371
* Requires https://github.com/readthedocs/common/pull/222

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
Looks great!

Perhaps eventually we'll want to pass around a `request` object instead of just the HTTP status, but let's just keep this in mind for now.

**Comment by humitos** [comment]
Hmm. Interesting... How could we inject the whole response/request object from CF? Could we pickle it somehow? If you have an idea, please open an issue explaining this so we can discuss/track it there

Having these objects around would be useful for other stuff for sure.

**Comment by agjohnson** [comment]
Not sure actually. I suppose if we find other users looking for other response attributes we can figure that out. I might just be thinking of a simple object we maintain to consolidate arguments we're passing around now, but I also don't have any other strong recommendations for other data we might need to pass around.

**Comment by humitos** [comment]
> I might just be thinking of a simple object we maintain to consolidate arguments we're passing around now

Good point. I  opened https://github.com/readthedocs/addons/issues/376 to discuss/track this work.

**Pull request merged**
