### PR TITLE
Fix the filters title covering other labels

### LINKED ISSUE #293: Search: style difference between Firefox and Chrome
We found this in our own docs: https://docs.readthedocs.io/en/latest/

Screenshot_2024-04-18_17-50-28

### PR DESCRIPTION
**Pull request by zanderle**
Fix #293 

There's still a slight difference. The only way to avoid that completely, would be to remove the default checkbox, and style our own. But I'm not really keen on that solution. 

BTW this styling/positioning will probably be further improved in #292 , so this is just a quick solution to make it look better.

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
This is totally reasonable. Honestly, I'm not sure these elements really need to be absolutely positioned, but you work with what you have...

Looks good :+1:

**Comment by humitos** [comment]
In my tests, the checkbox is still covered by the "Filters" border/padding or similar in Chrome. I'm having the same behavior reported in the issue. @zanderle can you share a screenshot on how it behaves for you?

**Comment by humitos** [comment]
@zanderle were you able to take a look at this?

**Comment by zanderle** [comment]
Should be ok now. Sorry for the delay.

Screenshot 2024-10-18 at 11 23 32

**Pull request merged**
