### PR TITLE
Docdiff: initial work to toggle enabled/disabled

### LINKED ISSUE #11: Docdiff: investigate why it breaks other integrations
Docdiff works correctly currently. However, I had to disable it for now because it interferes with other integrations like EthicalAds and Search As You Type.

I assume that it breaks because it changes the DOM and it may be removing some things required for the other integrations? 🤷🏼

### LINKED ISSUE #23: Docdiff: integrate nicely
_Description in progress (I'll be editing it)_

How do we want to integrate with docdiff?

- enable by default on PRs
- ability disable and re-enable by the reader
- as a reader, how I can decide how to diff? show only additions, show only removals, both?
- etc

References: https://github.com/readthedocs/meta/discussions/38

### LINKED ISSUE #62: Make `<readthedocs-docdiff>` an addon
https://www.w3schools.com/howto/howto_css_switch.asp

Screenshot_2023-04-24_16-43-29

I'd like to have this "toggle" accessible for theme authors to be able to put in their on page. We can think about adding it to the flyout. See #53

### PR DESCRIPTION
**Pull request by humitos**
Peek 2023-04-25 16-43

Closes #62 
Closes #23 
Closes #11

### CODE REVIEW

**Comment by humitos** [comment]
I added a smaller example in the `public/` folder so we can test it locally and play with it.

Peek 2023-04-27 15-49

**Comment by humitos** [comment]
Note that I'm not putting this anywhere in the page automatically for now. I think this will probably be part of #53 instead.

**Comment by humitos** [comment]
I've used `Control + Shift + f` as the hotkey for now. I'd appreciate other ideas here, but we will need to discuss about a more general "hotkey pattern" we want to follow with all our addons. It works great for now:

Peek 2023-07-13 15-52

**Comment by humitos** [comment]
I'd like to have a review here so we can merge it and start testing it in our projects at least.

**Comment by humitos** [comment]
> I've used `Control + Shift + f` as the hotkey for now

I reverted this decision and use single-stroke `d` after researching a little more about this in #80

**Comment by agjohnson** [comment]
Just a note here for now, but I could see this implementation drifting closer to either a multiposition slider, pair of toggle bars, or even just a dropdown instead (I lean towards this). There are a few modes that I'm finding useful, depending on the pull request contents:

- On, show deletes and additions
- On, only show additions
- Off

This doesn't need to affect the direction here yet, but will be something we want to consider in the future. Just noting so we don't cement too much of our implementation around a single, binary toggle bar. For the purpose of turning the diff off, this likely works fine for now.

**Comment by humitos** [comment]
I'm going to merge this because it's working fine. The only way to discover this feature right now is by hitting `d` when viewing a Pull Request. I will be promoting slowly this to start getting feedback.

We can easily disable from the API response if we notice it breaks for some reason.

**Pull request merged**
